- name: APK action
  # You may pin to the exact commit or the version.
  # uses: WaterLemons2k/apk-action@6872ea1c0a08c2646b5a9cfd7d5262659050c0ff
  uses: WaterLemons2k/apk-action@v1.1.2
  with:
    # Contents of the keystore file (.jks), base64 encoded
    keystore: 
    # Password of the keystore
    keystore-password: 
    # Alias of the key
    key-alias: 
    # Password of the key
    key-password: 
    # The Java version to set up
    java-version: # optional
    # The arguments passed to Gradle
    gradle-args: # optional, default is --no-daemon
    # Build a release or debug APK
    release: # optional, default is true
